version: "3"

services:
  app:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: reclame-backend
    restart: always

    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html